export enum MessageType {
  SENSOR_READING = 'SENSOR_READING',
  CONFIG_UPDATE = 'CONFIG_UPDATE',
  UPDATE_PREPARE = 'UPDATE_PREPARE',
  UPDATE_CHUNK = 'UPDATE_CHUNK',
  UPDATE_FINALIZE = 'UPDATE_FINALIZE',
  UPDATE_ROLLBACK = 'UPDATE_ROLLBACK',
  DEVICE_STATUS = 'DEVICE_STATUS',
  COMMAND = 'COMMAND',
}

export enum MessagePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ConnectionState {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  CONNECTION_LOST = 'CONNECTION_LOST',
  RECONNECTING = 'RECONNECTING',
} 