version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensorhub-api
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - sensorhub-network
    command: npm run start:dev

  postgres:
    image: postgres:14-alpine
    container_name: sensorhub-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sensorhub-network

  redis:
    image: redis:alpine
    container_name: sensorhub-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - sensorhub-network

networks:
  sensorhub-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 